[package]
name = "bgg_encoding"
version = "0.1.0"
edition = "2021"

[dependencies]
openfhe = { git = "https://github.com/MachinaIO/openfhe-rs.git", branch = "feat/sampler" }
phantom-zone-crypto = { git = "https://github.com/gausslabs/phantom-zone", branch = "rewrite", features = [
    "dev",
] }
phantom-zone-math = { git = "https://github.com/gausslabs/phantom-zone", branch = "rewrite", features = [
    "dev",
    "serde",
] }
rand = { version = "0.8.5", default-features = false, features = ["std_rng"] }
thiserror = "2.0.11"
serde = { version = "1.0.218", features = ["derive"] }
nalgebra = { version = "0.33.0", features = ["rand", "sparse"] }
serde_json = "1.0.64"
itertools = "0.11.0"
