ring_dimension = 8192
crt_depth = 10
crt_bits = 51
base_bits = 10
switched_modulus = "11356855067118857664833184493663073617295503237517702901294110480604358898435280304496557488628709959709944783957871923991226777337856"
d = 1
input_size = 32
level_width = 8
encoding_sigma = 1.4554e7
hardcoded_key_sigma = 1.2285e81
p_sigma = 1.5892e1
input = [
    true,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
]
