name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  fmt:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@nightly
        with:
          components: rustfmt
      - run: cargo +nightly fmt --all --check
          
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@nightly
        with:
          components: clippy

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake libgmp-dev

      - name: Cache OpenFHE build
        id: openfhe-cache
        uses: actions/cache@v4
        with:
          path: openfhe/build
          key: ${{ runner.os }}-openfhe-${{ hashFiles('openfhe/**/CMakeLists.txt') }}

      - name: Checkout OpenFHE
        uses: actions/checkout@v4
        with:
          repository: openfheorg/openfhe-development
          path: openfhe

      - name: Build OpenFHE
        if: steps.openfhe-cache.outputs.cache-hit != 'true'
        run: |
          cd openfhe
          mkdir -p build && cd build
          cmake ..
          make -j"$(nproc)"
          sudo make install

      - name: Update dynamic linker cache
        run: |
          echo "/usr/local/lib" | sudo tee /etc/ld.so.conf.d/openfhe.conf
          sudo ldconfig
          
      - name: Run clippy
        run: cargo +nightly clippy --workspace --all-targets --all-features
        env:
          RUSTFLAGS: -A unused

      - name: Run test
        run: cargo test --features="parallel"
  
  ci-success:
    name: ci success
    runs-on: ubuntu-latest
    if: always()
    needs:
      - build
      - fmt
    steps:
      - name: Decide whether the needed jobs succeeded or failed
        uses: re-actors/alls-green@release/v1
        with:
          jobs: ${{ toJSON(needs) }}