name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable

      - name: Install dependencies
        run: |
          sudo apt-get update
          # You may need additional packages depending on OpenFHE requirements
          sudo apt-get install -y build-essential cmake libgmp-dev

      - name: Checkout OpenFHE
        uses: actions/checkout@v2
        with:
          repository: openfheorg/openfhe-development
          path: openfhe

      - name: Build OpenFHE
        run: |
          cd openfhe
          mkdir build && cd build
          cmake ..
          make -j$(nproc)

      - name: Install clippy
        run: rustup component add clippy

      - name: Install rustfmt
        run: rustup component add rustfmt

      - name: Run clippy for native
        run: cargo clippy --all --all-targets -- -D warnings

      - name: Run fmt
        run: cargo fmt -- --check

      - name: Run tests
        run: cargo test --all --all-targets -- --nocapture