name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake libgmp-dev

      - name: Cache Rust dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Cache OpenFHE build
        uses: actions/cache@v3
        with:
          path: openfhe/build
          key: ${{ runner.os }}-openfhe-${{ hashFiles('openfhe/CMakeLists.txt') }}
          restore-keys: |
            ${{ runner.os }}-openfhe-

      - name: Checkout OpenFHE
        uses: actions/checkout@v2
        with:
          repository: openfheorg/openfhe-development
          path: openfhe

      - name: Build OpenFHE
        run: |
          cd openfhe
          mkdir -p build && cd build
          cmake ..
          make -j"$(nproc)"
          sudo make install

      - name: Update dynamic linker cache
        run: |
          echo "/usr/local/lib" | sudo tee /etc/ld.so.conf.d/openfhe.conf
          sudo ldconfig

      - uses: taiki-e/install-action@cargo-llvm-cov
      - uses: taiki-e/install-action@nextest
      - name: Install clippy and rustfmt
        run: |
          rustup component add clippy
          rustup component add rustfmt
      - uses: taiki-e/install-action@just
      - name: Run ci
        run: just ci