name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake libgmp-dev

      - name: Setup Rust toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
          components: clippy, rustfmt

      - name: Cache Rust dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: Cache OpenFHE source
        uses: actions/cache@v3
        with:
          path: openfhe
          key: ${{ runner.os }}-openfhe-source-${{ hashFiles('openfhe/CMakeLists.txt') }}
          restore-keys: |
            ${{ runner.os }}-openfhe-source-

      - name: Checkout OpenFHE if not cached
        if: steps.cache-openfhe-source.outputs.cache-hit != 'true'
        uses: actions/checkout@v3
        with:
          repository: openfheorg/openfhe-development
          path: openfhe

      - name: Cache OpenFHE build
        id: cache-openfhe-build
        uses: actions/cache@v3
        with:
          path: |
            /usr/local/include/openfhe
            /usr/local/lib/libOPENFHE*
          key: ${{ runner.os }}-openfhe-build-${{ hashFiles('openfhe/CMakeLists.txt') }}
          restore-keys: |
            ${{ runner.os }}-openfhe-build-

      - name: Build and install OpenFHE
        if: steps.cache-openfhe-build.outputs.cache-hit != 'true'
        run: |
          cd openfhe
          mkdir -p build && cd build
          cmake .. -DCMAKE_BUILD_TYPE=Release
          make -j"$(nproc)"
          sudo make install
          sudo ldconfig

      - uses: taiki-e/install-action@v2
        with:
          tool: cargo-llvm-cov,nextest,just

      - name: Run CI tasks
        run: just ci